/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ToursRouteImport } from './routes/tours'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as EventsSlugIndexRouteImport } from './routes/events.$slug.index'
import { Route as EventsSlugBookRouteImport } from './routes/events.$slug.book'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursRoute = ToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugIndexRoute = EventsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsSlugRoute,
} as any)
const EventsSlugBookRoute = EventsSlugBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => EventsSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/login': typeof LoginRoute
  '/tours': typeof ToursRoute
  '/events/$slug': typeof EventsSlugRouteWithChildren
  '/events/$slug/book': typeof EventsSlugBookRoute
  '/events/$slug/': typeof EventsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/login': typeof LoginRoute
  '/tours': typeof ToursRoute
  '/events/$slug/book': typeof EventsSlugBookRoute
  '/events/$slug': typeof EventsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/login': typeof LoginRoute
  '/tours': typeof ToursRoute
  '/events/$slug': typeof EventsSlugRouteWithChildren
  '/events/$slug/book': typeof EventsSlugBookRoute
  '/events/$slug/': typeof EventsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booking'
    | '/login'
    | '/tours'
    | '/events/$slug'
    | '/events/$slug/book'
    | '/events/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking'
    | '/login'
    | '/tours'
    | '/events/$slug/book'
    | '/events/$slug'
  id:
    | '__root__'
    | '/'
    | '/booking'
    | '/login'
    | '/tours'
    | '/events/$slug'
    | '/events/$slug/book'
    | '/events/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingRoute: typeof BookingRoute
  LoginRoute: typeof LoginRoute
  ToursRoute: typeof ToursRoute
  EventsSlugRoute: typeof EventsSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours': {
      id: '/tours'
      path: '/tours'
      fullPath: '/tours'
      preLoaderRoute: typeof ToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug/': {
      id: '/events/$slug/'
      path: '/'
      fullPath: '/events/$slug/'
      preLoaderRoute: typeof EventsSlugIndexRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/events/$slug/book': {
      id: '/events/$slug/book'
      path: '/book'
      fullPath: '/events/$slug/book'
      preLoaderRoute: typeof EventsSlugBookRouteImport
      parentRoute: typeof EventsSlugRoute
    }
  }
}

interface EventsSlugRouteChildren {
  EventsSlugBookRoute: typeof EventsSlugBookRoute
  EventsSlugIndexRoute: typeof EventsSlugIndexRoute
}

const EventsSlugRouteChildren: EventsSlugRouteChildren = {
  EventsSlugBookRoute: EventsSlugBookRoute,
  EventsSlugIndexRoute: EventsSlugIndexRoute,
}

const EventsSlugRouteWithChildren = EventsSlugRoute._addFileChildren(
  EventsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingRoute: BookingRoute,
  LoginRoute: LoginRoute,
  ToursRoute: ToursRoute,
  EventsSlugRoute: EventsSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
