/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as EventsSlugBookRouteImport } from './routes/events.$slug.book'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugBookRoute = EventsSlugBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => EventsSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events/$slug': typeof EventsSlugRouteWithChildren
  '/events/$slug/book': typeof EventsSlugBookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events/$slug': typeof EventsSlugRouteWithChildren
  '/events/$slug/book': typeof EventsSlugBookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events/$slug': typeof EventsSlugRouteWithChildren
  '/events/$slug/book': typeof EventsSlugBookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/events/$slug' | '/events/$slug/book'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/events/$slug' | '/events/$slug/book'
  id: '__root__' | '/' | '/events/$slug' | '/events/$slug/book'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsSlugRoute: typeof EventsSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug/book': {
      id: '/events/$slug/book'
      path: '/book'
      fullPath: '/events/$slug/book'
      preLoaderRoute: typeof EventsSlugBookRouteImport
      parentRoute: typeof EventsSlugRoute
    }
  }
}

interface EventsSlugRouteChildren {
  EventsSlugBookRoute: typeof EventsSlugBookRoute
}

const EventsSlugRouteChildren: EventsSlugRouteChildren = {
  EventsSlugBookRoute: EventsSlugBookRoute,
}

const EventsSlugRouteWithChildren = EventsSlugRoute._addFileChildren(
  EventsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsSlugRoute: EventsSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
